#!/bin/sh
# Entrypoint for the k8s-runner component's `k8s-operator` service: install the Teleport
# CRDs into the disposable cluster and roll out the operator built from the clone.
#
# Deliberately NOT `set -e` on the apply steps: a CRD or manifest that the API server
# rejects is often the very thing under test, so we log the failure and keep going —
# the checks decide whether that's fatal.
set -u
. /scripts/k8s-common.sh

: "${TELEPORT_HOST:?TELEPORT_HOST required}"
: "${OPERATOR_MANIFEST:=/manifests/k8s-operator.yaml}"
: "${CRD_DIR:=/crds}"

k8s_wait_ready || { echo "[operator] cluster never came up" >&2; k8s_done /tmp/operator-failed; }

# --- CRDs --------------------------------------------------------------------
# --server-side is required, not stylistic: the Teleport role CRDs are far larger than
# the 256KB last-applied-configuration annotation a client-side apply would write.
echo "[operator] installing CRDs from $CRD_DIR"
crd_ok=0; crd_fail=0
for f in "$CRD_DIR"/*.yaml; do
  [ -e "$f" ] || continue
  if kubectl apply --server-side --force-conflicts -f "$f" >/dev/null 2>&1; then
    crd_ok=$((crd_ok + 1))
  else
    crd_fail=$((crd_fail + 1))
    echo "[operator] CRD FAILED: $(basename "$f")"
    kubectl apply --server-side --force-conflicts -f "$f" 2>&1 | sed 's/^/[operator]   /'
  fi
done
echo "[operator] CRDs installed: $crd_ok ok, $crd_fail failed"
kubectl wait --for=condition=Established --timeout=60s \
  crd/teleportprovisiontokens.resources.teleport.dev 2>&1 | sed 's/^/[operator] /'

# --- the operator itself -----------------------------------------------------
# Pods get an autogenerated resolv.conf pointing at CoreDNS, which forwards upstream and
# has no idea what a docker container name is — so the operator cannot resolve the
# Teleport cluster by name the way a sibling container can. Resolve it out here, where
# docker's embedded DNS is available, and pin it into the pod with hostAliases.
auth_ip="$(resolve_ip "$TELEPORT_HOST")"
if [ -z "$auth_ip" ]; then
  echo "[operator] could not resolve $TELEPORT_HOST" >&2
  k8s_done /tmp/operator-failed
fi
echo "[operator] $TELEPORT_HOST -> $auth_ip (pinned into the pod via hostAliases)"

sed "s/__TELEPORT_AUTH_IP__/$auth_ip/g" "$OPERATOR_MANIFEST" > /tmp/k8s-operator.yaml
kubectl apply -f /tmp/k8s-operator.yaml 2>&1 | sed 's/^/[operator] /'

echo "[operator] waiting for rollout ..."
kubectl -n teleport rollout status deploy/teleport-operator --timeout=240s 2>&1 | sed 's/^/[operator] /'

# Always dump the operator's own view — on success it shows the successful bot join, and
# on failure it is the first thing anyone reading the report will want.
kubectl -n teleport get pods -o wide 2>&1 | sed 's/^/[operator] /'
echo "[operator] ---- operator logs ----"
kubectl -n teleport logs deploy/teleport-operator --tail=60 2>&1 | sed 's/^/[operator] /'

k8s_done /tmp/operator-ready
