#!/bin/sh
# scoped_usage_mode actor.
#
# Drives two things and RECORDS what it saw; it never judges. Every case appends one record to
# /out/observations.json and the module's `observation_equals` checks do the asserting, so the
# expected outcome for each join method lives in module.yaml (one line per method) rather than
# in this script.
#
# 1. ADMISSION MATRIX — for every join method validateJoinMethod knows, try to create a scoped
#    Node token with `usage_mode: single_use` AND the same token with `usage_mode: unlimited`.
#    The unlimited twin is the control: it shares the method spec byte for byte, so when it is
#    accepted and the single_use one is rejected, the usage mode is the only thing that differs.
#    Without it a typo in a method spec would read as "single_use correctly denied".
#
#      case admit-<method>-<usage_mode>
#      after.accepted                 yes|no
#      after.rejected_for_usage_mode  yes|no — the error names usage_mode (any wording: the
#                                     generic allowlist error, github/gitlab's older per-method
#                                     one, and the bot "must be 'bot'" one all do)
#      after.error                    tctl's stderr, verbatim
#
#    Plus one BOT case (pre-existing behavior, not this change): a bot token can never be
#    single_use, which is why single_use only ever matters for agent joins.
#
# 2. TOKEN STATUS — after the agents join, read each JOIN token (the ones bootstrap created for
#    the agents in services.yml.j2) and record whether the join consumed it.
#
#      case status-su-<short>-<mode>
#      after.first_joined   yes|no — the pair's FIRST agent was registered before the snapshot
#      after.second_joined  yes|no — same for the SECOND (informational for single_use tokens)
#      after.usage_status   single_use | bound_keypair | none — which status.usage oneof is set
#      after.consumed       yes|no — status.usage.single_use.used_by_fingerprint is non-empty
#      after.used_at / after.reusable_until   raw timestamps, for the report
#
#    The node barrier matters for the unlimited control: "not consumed" is only meaningful if a
#    host actually joined with the token first, so its snapshot waits for BOTH agents.
#
# No `set -e`: a case that goes wrong must still be RECORDED. A missing record is
# indistinguishable from a crashed actor; a recorded bad value is a finding.
set -u

TCTL="tctl --identity ${IDENTITY} --auth-server ${AUTH_ADDR}"
OBS=/out/observations.json
REC=/tmp/records
SCOPE="${SCOPE:?}"
ACTOR=scripts/actor.sh
mkdir -p /out "$REC"

log() { echo "[su-actor] $*"; }
now() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# Merge every per-case record into the observations file. Called after each phase so a
# slow later phase never hides the results of an earlier one.
publish() {
    jq -s 'sort_by(.case)' "$REC"/*.json > "$OBS.tmp" 2>/dev/null && mv "$OBS.tmp" "$OBS"
    log "published $(jq length "$OBS" 2>/dev/null || echo 0) record(s)"
}

###############################################################################
# 0. Wait for the identity (the idbot writes it; the healthcheck gates us, but be safe).
###############################################################################
i=0
until [ -s "$IDENTITY" ] && $TCTL get scoped_token >/dev/null 2>&1; do
    i=$((i + 1)); [ "$i" -ge 60 ] && { log "FATAL: identity never usable"; break; }
    sleep 2
done

###############################################################################
# 1. Admission matrix.
###############################################################################

# Minimal VALID per-method config, indented to sit under `spec:`. Each satisfies its
# validate<Method>() in lib/scopes/joining/token.go and nothing more; values are inert (no
# token here is ever joined with). The unlimited control proves each one is valid.
spec_for() {
    case "$1" in
        token) ;;  # status.secret is generated by maybeSetTokenSecret on create
        ec2) cat <<'EOF'
  aws:
    allow:
      - aws_account: "123456789012"
EOF
        ;;
        iam) cat <<'EOF'
  aws:
    allow:
      - aws_account: "123456789012"
EOF
        ;;
        gcp) cat <<'EOF'
  gcp:
    allow:
      - project_ids: [harness-project]
EOF
        ;;
        azure) cat <<'EOF'
  azure:
    allow:
      - subscription: 00000000-0000-0000-0000-000000000000
EOF
        ;;
        azure_devops) cat <<'EOF'
  azure_devops:
    organization_id: 00000000-0000-0000-0000-000000000000
    allow:
      - project_name: harness
EOF
        ;;
        oracle) cat <<'EOF'
  oracle:
    allow:
      - tenancy: ocid1.tenancy.oc1..harness
EOF
        ;;
        kubernetes) cat <<'EOF'
  kubernetes:
    type: in_cluster
    allow:
      - service_account: "default:harness"
EOF
        ;;
        bound_keypair) cat <<'EOF'
  bound_keypair:
    onboarding:
      registration_secret: harness-admission-secret
EOF
        ;;
        generic_oidc) cat <<'EOF'
  generic_oidc:
    issuer: https://issuer.invalid
    audience: harness
    allow_any:
      - conditions:
          - attribute: sub
            eq:
              value: harness
EOF
        ;;
        github) cat <<'EOF'
  github:
    allow:
      - repository: harness/harness
EOF
        ;;
        gitlab) cat <<'EOF'
  gitlab:
    allow:
      - project_path: harness/harness
EOF
        ;;
        tpm) cat <<'EOF'
  tpm:
    allow:
      - ek_public_hash: "0000000000000000000000000000000000000000000000000000000000000000"
EOF
        ;;
        circleci) cat <<'EOF'
  circleci:
    organization_id: 00000000-0000-0000-0000-000000000000
    allow:
      - project_id: 00000000-0000-0000-0000-000000000000
EOF
        ;;
        bitbucket) cat <<'EOF'
  bitbucket:
    audience: harness
    identity_provider_url: https://api.bitbucket.org/2.0/workspaces/harness/pipelines-config/identity/oidc
    allow:
      - workspace_uuid: "{00000000-0000-0000-0000-000000000000}"
EOF
        ;;
        terraform_cloud) cat <<'EOF'
  terraform_cloud:
    allow:
      - organization_name: harness
        workspace_name: harness
EOF
        ;;
        spacelift) cat <<'EOF'
  spacelift:
    hostname: harness.app.spacelift.io
    allow:
      - space_id: root
EOF
        ;;
        env0) cat <<'EOF'
  env0:
    allow:
      - organization_id: 00000000-0000-0000-0000-000000000000
        project_name: harness
EOF
        ;;
    esac
}

# admit <case> <method> <usage_mode> <roles> [<extra spec lines>]
admit() {
    _case=$1; _method=$2; _usage=$3; _roles=$4; _extra=${5:-}
    _name=$(printf '%s' "$_case" | tr '_' '-')
    _file=/tmp/admit/$_case.yaml
    mkdir -p /tmp/admit
    {
        printf 'kind: scoped_token\nversion: v1\nmetadata:\n  name: %s\nscope: "%s"\nspec:\n' "$_name" "$SCOPE"
        printf '  roles: [%s]\n  join_method: %s\n  usage_mode: %s\n' "$_roles" "$_method" "$_usage"
        [ -n "$_extra" ] && printf '%s\n' "$_extra"
        spec_for "$_method"
    } > "$_file"

    # tctl colors its ERROR prefix; strip ANSI escapes so the recorded error reads cleanly.
    if _out=$($TCTL create -f "$_file" 2>&1); then _acc=yes; else _acc=no; fi
    _out=$(printf '%s' "$_out" | sed 's/\x1b\[[0-9;]*m//g')
    if [ "$_acc" = no ] && printf '%s' "$_out" | grep -Eiq 'usage[_ ]mode'; then _rfu=yes; else _rfu=no; fi
    log "$_case: accepted=$_acc usage_mode_rejection=$_rfu"

    jq -n --arg case "$_case" --arg at "$(now)" --arg actor "$ACTOR" --arg token "$SCOPE::$_name" \
          --arg applied "$_method usage_mode=$_usage roles=[$_roles]" \
          --arg acc "$_acc" --arg rfu "$_rfu" --arg err "$([ "$_acc" = yes ] && echo '' || printf '%s' "$_out")" \
          --arg spec "$(cat "$_file")" \
          '{case: $case, at: $at, actor: $actor, token: $token, applied: $applied,
            before: {}, after: {accepted: $acc, rejected_for_usage_mode: $rfu, error: $err, resource: $spec}}' \
          > "$REC/$_case.json"
}

METHODS="token ec2 iam gcp azure azure_devops oracle kubernetes bound_keypair generic_oidc github gitlab tpm circleci bitbucket terraform_cloud spacelift env0"

log "admission matrix: $(echo "$METHODS" | wc -w) methods x {single_use, unlimited}"
# In parallel: each tctl call is an emulated amd64 process start, and the whole module has
# to finish inside run-plan's verify window.
for m in $METHODS; do
    for u in single_use unlimited; do
        admit "admit-$m-$u" "$m" "$u" "Node" "  assigned_scope: \"$SCOPE\"" &
    done
done
# Bot case: same kubernetes spec, Bot role. Pre-existing rule (strongValidateBotToken).
admit "admit-bot-single_use" kubernetes single_use Bot "  bot: \"$SCOPE::su-nobody\"" &
wait
publish

###############################################################################
# 2. Join-token status, after the agents join.
###############################################################################

node_joined() { # node_joined <hostname> -> yes|no
    if $TCTL get nodes --format json 2>/dev/null | jq -e --arg h "$1" \
            '(if type == "array" then . else [.] end) | any(.spec.hostname == $h)' >/dev/null 2>&1; then
        echo yes
    else
        echo no
    fi
}

# read the scoped token; normalizes array/object output and proto vs JSON field names.
token_json() {
    $TCTL get scoped_token "$SCOPE::$1" --format json 2>/dev/null \
        | jq -c 'if type == "array" then .[0] else . end' 2>/dev/null
}

status_of() { # status_of <token> <first-host> <second-host> <wait-for-second yes|no>
    _tok=$1; _first=$2; _second=$3; _want_second=$4
    i=0
    while [ "$i" -lt 90 ]; do
        _f=$(node_joined "$_first")
        _s=$(node_joined "$_second")
        if [ "$_f" = yes ] && { [ "$_want_second" = no ] || [ "$_s" = yes ]; }; then break; fi
        i=$((i + 1)); sleep 2
    done
    log "$_tok: first_joined=$_f second_joined=$_s (after ${i} polls)"

    # Consumption is written after the host certs are issued, so the node can register a beat
    # before the status write is readable. Give a single_use token a short grace to show it.
    j=0
    while :; do
        _t=$(token_json "$_tok")
        _fp=$(printf '%s' "$_t" | jq -r '(.status.usage.single_use // .status.usage.singleUse // {}) | (.used_by_fingerprint // .usedByFingerprint // "")')
        [ -n "$_fp" ] || [ "$_want_second" = yes ] || [ "$j" -ge 10 ] && break
        j=$((j + 1)); sleep 2
    done

    _us=$(printf '%s' "$_t" | jq -r '
        (.status.usage // {}) as $u
        | if ($u.single_use // $u.singleUse) != null then "single_use"
          elif ($u.bound_keypair // $u.boundKeypair) != null then "bound_keypair"
          else "none" end')
    _su=$(printf '%s' "$_t" | jq -c '.status.usage.single_use // .status.usage.singleUse // {}' 2>/dev/null)
    [ -n "$_su" ] || _su='{}'
    jq -n --arg case "status-$_tok" --arg at "$(now)" --arg actor "$ACTOR" --arg token "$SCOPE::$_tok" \
          --arg f "$_f" --arg s "$_s" --arg us "${_us:-none}" \
          --arg consumed "$([ -n "$_fp" ] && echo yes || echo no)" \
          --argjson su "$_su" --arg raw "${_t:-<unreadable>}" \
          '{case: $case, at: $at, actor: $actor, token: $token, applied: "joined by its agent pair",
            before: {}, after: {first_joined: $f, second_joined: $s, usage_status: $us,
                                consumed: $consumed,
                                used_at: ($su.used_at // $su.usedAt // ""),
                                reusable_until: ($su.reusable_until // $su.reusableUntil // ""),
                                token: $raw}}' > "$REC/status-$_tok.json"
}

for short in ${JOIN_SHORTS:?}; do
    status_of "su-$short-single"    "${CLUSTER_ID}-su-$short-single-first"    "${CLUSTER_ID}-su-$short-single-second"    no &
    status_of "su-$short-unlimited" "${CLUSTER_ID}-su-$short-unlimited-first" "${CLUSTER_ID}-su-$short-unlimited-second" yes &
done
wait
publish

log "done"
touch /tmp/actor-done
exec sleep infinity
